-- Cria a tabela de livros. Cada linha é um exemplar do acervo: dois exemplares
-- do mesmo título repetem o ISBN, por isso o isbn não é UNIQUE.
CREATE TABLE livros (
    -- Cria uma chave numérica gerada automaticamente pelo PostgreSQL.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Guarda o título obrigatório do livro.
    titulo VARCHAR(255) NOT NULL,
    -- Guarda o ISBN obrigatório; com os hífens, ele tem 17 caracteres.
    isbn VARCHAR(20) NOT NULL,
    -- Diz se o exemplar está na estante. Nasce verdadeiro; muda com empréstimo e devolução.
    disponivel BOOLEAN NOT NULL DEFAULT TRUE
);
