-- Cria a tabela de leitores: as pessoas cadastradas que podem pegar livros emprestados.
CREATE TABLE leitores (
    -- Cria uma chave numérica gerada automaticamente pelo PostgreSQL.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Guarda o nome obrigatório do leitor.
    nome VARCHAR(255) NOT NULL,
    -- Guarda o e-mail obrigatório do leitor.
    email VARCHAR(255) NOT NULL
);
