-- Cria a tabela de empréstimos: cada linha liga um leitor a um livro.
-- Vem depois de V1 e V2 porque referencia as duas tabelas.
CREATE TABLE emprestimos (
    -- Cria uma chave numérica gerada automaticamente pelo PostgreSQL.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Quem pegou o livro. REFERENCES cria a chave estrangeira: o PostgreSQL
    -- recusa um leitor_id que não exista em leitores(id).
    leitor_id BIGINT NOT NULL REFERENCES leitores (id),
    -- Qual livro foi emprestado, com a mesma garantia em livros(id).
    livro_id BIGINT NOT NULL REFERENCES livros (id),
    -- Dia em que o livro saiu da biblioteca.
    data_retirada DATE NOT NULL,
    -- Dia em que o livro voltou. Fica NULL enquanto o empréstimo está em aberto.
    data_devolucao DATE
);
