-- Exercício 6: cria a tabela de responsáveis cadastrados.
CREATE TABLE responsaveis (
    -- Cria uma chave numérica gerada automaticamente pelo PostgreSQL.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Guarda o nome obrigatório do responsável.
    nome VARCHAR(255) NOT NULL,
    -- Guarda o e-mail obrigatório do responsável.
    email VARCHAR(255) NOT NULL
);

-- Liga cada tarefa (lado "muitos") a no máximo um responsável (lado "um").
-- Aceita NULL: uma tarefa pode existir sem responsável vinculado.
-- REFERENCES cria a chave estrangeira: o PostgreSQL recusa um responsavel_id
-- que não exista em responsaveis(id).
ALTER TABLE tarefas ADD COLUMN responsavel_id BIGINT REFERENCES responsaveis (id);
